# -*- coding: utf-8 -*-
"""Q12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDhc-OvW2tQbtFoLaXLj5n4Ep6GO5JjF

# Question 12
"""

import numpy.linalg as lg


A= array([[4, -1, -1, -1],
         [-1, 3, 0, -1],
         [-1, 0, 3, -1],
         [-1, -1, -1, 4]], float)

v=array([5, 0 , 5, 0], float)
N=len(v)

lg.solve(A,v)
#This clearly gives the same answer